### PR TITLE
NPE during logging

### LINKED ISSUE #305: NPE in RecordStreamLogger.logVariables(
Running my tests in https://github.com/camunda-community-hub/camunda-cloud-examples/blob/c8/twitter-review-java-springboot/src/test/java/org/camunda/community/examples/twitter/TestTwitterProcess.java I just saw this NPE (which should simply not happen I guess) on `8.0.0`

```log
java.lang.NullPointerException: Cannot invoke "Object.toString()" because "value" is null
	at io.camunda.zeebe.process.test.filters.logger.RecordStreamLogger.lambda$logVariables$9(RecordStreamLogger.java:275)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at io.camunda.zeebe.process.test.filters.logger.RecordStreamLogger.logVariables(RecordStreamLogger.java:275)
	at io.camunda.zeebe.process.test.filters.logger.RecordStreamLogger.logProcessInstanceCreationRecordValue(RecordStreamLogger.java:238)
	at io.camunda.zeebe.process.test.filters.logger.RecordStreamLogger.lambda$logRecords$7(RecordStreamLogger.java:104)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
	at io.camunda.zeebe.process.test.filters.logger.RecordStreamLogger.logRecords(RecordStreamLogger.java:100)
	at io.camunda.zeebe.process.test.filters.logger.RecordStreamLogger.log(RecordStreamLogger.java:93)
	at io.camunda.zeebe.process.test.filters.RecordStream.print(RecordStream.java:125)
	at io.camunda.zeebe.spring.test.ZeebeTestExecutionListener.afterTestMethod(ZeebeTestExecutionListener.java:39)
```

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

Variable with a null value produce NPE when logging the record stream. This PR adds a null check and a bunch of tests for our logger to prevent this in the future.

## Related issues

closes #305 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to backport the fix

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually

Documentation:
* [ ] Javadoc has been written
* [ ] The documentation is updated

### CODE REVIEW

File: filters/src/test/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLoggerTest.java [hunk 1]
```diff
@@ -15,16 +15,56 @@
...
+import java.util.Date;
+import java.util.HashMap;
 import java.util.Map;
 import java.util.function.Function;
 import org.assertj.core.api.SoftAssertions;
 import org.junit.jupiter.api.Test;
 
 class RecordStreamLoggerTest {
 
+  private static final Map<String, Object> TYPED_TEST_VARIABLES = new HashMap<>();
```
Comment (pihme) [inline filters/src/test/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLoggerTest.java:58]: :x: I am not so sure these tests add much value. I think it would be better to make `logVariables(...)` in `RecordStreamLogger` protected and test this method in isolation. 

if you still want to keep those kinds of tests I would propose to go deep into jqwik and make "Does not throw an exception" a property and then refactor this to spend most of the time generating aribtrary records. I think this will be a better investment going forward

File: filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java [hunk 2]
```diff
@@ -272,7 +272,14 @@ private String logVariables(final Map<String, Object> variables) {
     }
 
     final StringJoiner joiner = new StringJoiner(", ", "[", "]");
-    variables.forEach((key, value) -> joiner.add(key + " -> " + value.toString()));
+    variables.forEach(
```
Comment (pihme) [inline filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java:275]: :wrench: This could also be rewritten to (pseudo code)
```
variables.entries().stream()
   .map( (key, value) -> key + " -> " +  value == null ? "null" :  value )
   .collect(Collectors.joining(", "));
```

**Review by pihme — CHANGES_REQUESTED** [review]
Change looks good. I think the tests should be looked at again.

File: filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java (hunk 2 above)
Comment (pihme) [reply filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java:275]: Or even simpler:
` variables.forEach((key, value) -> joiner.add(key + " -> " + value()));`

**Review by pihme — APPROVED** [review]
