### PR TITLE
Configure a custom mapper

### LINKED ISSUE #581: @ZeebeProcessTest is causing the failure of an obvious Parameterized test
Using **Testcontainers (JDK 8+)**, I was running some tests scenarios. 
All my tests are succdeding except tests annotated by **@ParameterizedTest**. 
When I extract the parameterized test  code on a simple test method annotated by **@Test**, It works and the test succeed. 

I can reproduce the same issue with the same error returned using an obvious parameterized test. 
And i found so weird that having ZeebeProcessTest annotation (that could be combined with MockitoExtension) could be the source of an error caused by an obvious test scenario. 

Here my simple test class, 

```
import io.camunda.zeebe.client.ZeebeClient;
import io.camunda.zeebe.process.test.extension.testcontainer.ContainerizedEngine;
import io.camunda.zeebe.process.test.extension.testcontainer.ZeebeProcessTest;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

@ZeebeProcessTest
class TestClass {
    ContainerizedEngine engine;
    ZeebeClient client;

    @ParameterizedTest
    @ValueSource(strings = {"A", "B", "C"})
    void test(String letters){
        Assertions.assertThat(1).isEqualTo(1);
    }

}

```

The dependency used 
```
                <groupId>io.camunda</groupId>
                <artifactId>zeebe-process-test-extension-testcontainer</artifactId>
                <version>8.1.3</version>
                <scope>test</scope>

```

And here the stack trace 

```
24, 2022 11:50:28 PM org.junit.jupiter.engine.descriptor.MethodBasedTestDescriptor lambda$invokeTestWatchers$3
WARNING: Failed to invoke TestWatcher [io.camunda.zeebe.process.test.extension.testcontainer.ZeebeProcessTestExtension] for method [<package>.TestClass#test(java.lang.String)] with display name [[1] letters=A]
java.lang.NullPointerException
	at io.camunda.zeebe.process.test.extension.testcontainer.ZeebeProcessTestExtension.testFailed(ZeebeProcessTestExtension.java:121)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$nodeFinished$15(TestMethodTestDescriptor.java:303)
	at org.junit.jupiter.engine.descriptor.MethodBasedTestDescriptor.lambda$invokeTestWatchers$3(MethodBasedTestDescriptor.java:134)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.jupiter.engine.descriptor.MethodBasedTestDescriptor.invokeTestWatchers(MethodBasedTestDescriptor.java:132)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.nodeFinished(TestMethodTestDescriptor.java:294)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.nodeFinished(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.reportCompletion(NodeTestTask.java:188)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:100)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:226)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:204)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:139)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.lambda$execute$2(TestTemplateTestDescriptor.java:107)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:107)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:42)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

### LINKED ISSUE #724: Ability to configure a custom Jackson Mapper
Hello, when using the production ZeebeClient with Spring, it's possible to configure a custom Jackson mapper by exposing a bean named `zeebeObjectMapper`. Here for instance I can pass my own mapper configured with the JSR-310 module to serialize java.time objects.

When using the test client provided by this library however, I can't find a way to override the mapper, so the tests are failing if I try to serialize java.time objects.

Is there a way to configure the mapper at test startup?

### PR DESCRIPTION
**Pull request by nicpuppa**
## Description

With this PR we enable users to provide a custom `ObjectMapper` to the `Zeebe Client`. 

Users should simply create and configure their mapper in the test classes annotated with `@ZeebeProcessTest`.
When creating the `Zeebe Client`, if an `ObjectMapper` is instanciated. The annotation will configure that mapper into the client.

## Related issues

closes #724 
closes #581 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to backport the fix

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually

Documentation:
* [x] Javadoc has been written
* [x] The documentation is updated

### CODE REVIEW

**Comment by nicpuppa** [comment]
Hi @remcowesterhoud, with this solution we have a problem with `revapi`. I want to discuss with you the possibility to add this breaking change. For now I marked this PR as draft

**Review by remcowesterhoud — COMMENTED** [review]
> Hi @remcowesterhoud, with this solution we have a problem with `revapi`. I want to discuss with you the possibility to add this breaking change. For now I marked this PR as draft

@nicpuppa Adding a method like this is fine. We can exclude it from revapi. Please also sign the CLA and re request my review when you're done 🙂

**Comment by nicpuppa** [comment]
Hi @remcowesterhoud, this PR is ready to be reviewed 🙇

File: api/src/main/java/io/camunda/zeebe/process/test/api/ZeebeTestEngine.java [hunk 1]
```diff
@@ -87,4 +88,9 @@ public interface ZeebeTestEngine {
    * @throws TimeoutException if the engine has not reached a busy state before the timeout
    */
   void waitForBusyState(Duration timeout) throws InterruptedException, TimeoutException;
+
+  /**
+   * @return a newly created {@link ZeebeClient} with custom mapper
+   */
+  ZeebeClient createClientWithCustomMapper(ObjectMapper customObjectMapper);
```
Comment (remcowesterhoud) [inline api/src/main/java/io/camunda/zeebe/process/test/api/ZeebeTestEngine.java:95]: ❌ Let's overload the existing method and put it under the existing method in this interface for easier readability.

File: extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/ZeebeProcessTestExtension.java [hunk 2]
```diff
@@ -165,4 +172,25 @@ private void injectField(
...
+    if (!customMapperOpt.isPresent()) {
+      return null;
+    }
+    final Field customMapper = customMapperOpt.get();
+    ReflectionUtils.makeAccessible(customMapper);
+    try {
+      return (ObjectMapper) customMapper.get(context.getRequiredTestInstance());
+    } catch (final IllegalAccessException e) {
+      throw new RuntimeException(e);
+    }
```
Comment (remcowesterhoud) [inline extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/ZeebeProcessTestExtension.java:194]: ❌ I'm not a big fan of configuring the ObjectMapper this way. At first It thought it would be elegant, but I don't like messing with the accessibility of a field that we don't overwrite the value of (like we do with the engine and client).

I also don't believe it's sufficient to configure the ObjectMapper like this, cause it's only changed in the client now. More on that in another comment.

Comment (remcowesterhoud) [reply extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/ZeebeProcessTestExtension.java:194]: Same comment goes for the other extension class of course.

File: README.md [hunk 3]
```diff
@@ -215,6 +215,25 @@ IncidentAssert assertions = BpmnAssert.assertThat(activatedJob)
...
+
+
+  private ObjectMapper setupMapper() {
+    ObjectMapper objectMapper = new ObjectMapper();
+    .... // custom configuration
+    return objectMapper;
+  }
+}
+```
+
```
Comment (remcowesterhoud) [inline README.md:236]: 🔧 If the extension manages this we should add this to the `Annotation` section of the README.

File: README.md [hunk 4]
```diff
@@ -215,6 +215,25 @@ IncidentAssert assertions = BpmnAssert.assertThat(activatedJob)
   .extractingLatestIncident();
 ```
 
+### Custom Mapper
+
+Users can now provide their own `ObjectMapper` to the `Zeebe Client`
```
Comment (remcowesterhoud) [inline README.md:220]: 🔧 Instead of saying users can _now_ use it, let's keep it independent from a time. Something along the lines of

"A custom `ObjecctMapper` can be provided" and then explaining how to do that.

**Review by remcowesterhoud — CHANGES_REQUESTED** [review]
Thanks for the changes @nicpuppa  and sorry for taking so long to review them 🙇 

❌ You've missed a part of the change. In the [VariablesMapAssert](https://github.com/camunda/zeebe-process-test/blob/main/assertions/src/main/java/io/camunda/zeebe/process/test/assertions/VariablesMapAssert.java#L35-L40) we also use the `ObjectMapper` to verify a variable matches the expected value. We must make sure that if a custom `ObjectMapper` is provided we use it both the client and these assertions.

We should also have a testcase that verifies if this works. E.g.:
1. Start a process with a date time serialised using the client.
2. Assert that the process contains the variable as expected, deserialising in the `VariablesMapAssert`.

------------

Because we need to use this ObjectMapper is multiple places we'll have to store it somewhere where the assertions can also access it. We do similar for the `RecordStream` that we can do for this as well. I'd propose having it in some sort of config class though.

File: extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/ZeebeProcessTestExtension.java [hunk 5]
```diff
@@ -78,10 +81,14 @@ public void beforeAll(final ExtensionContext extensionContext) {
   @Override
   public void beforeEach(final ExtensionContext extensionContext) {
     final Object engineContent = getStore(extensionContext.getParent().get()).get(KEY_ZEEBE_ENGINE);
+    final ObjectMapper customObjectMapper = getCustomMapper(extensionContext);
```
Comment (remcowesterhoud) [inline extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/ZeebeProcessTestExtension.java:84]: 🔧 Let's work with `Optionals` instead of returning a `null` if the custom object mapper is not available.

Same goes for the other extension of course.

Comment (nicpuppa) [reply extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/ZeebeProcessTestExtension.java:84]: Nice suggestion ❤️

**Comment by nicpuppa** [comment]
Hi @remcowesterhoud, thank you for the review and the nice suggestion 🙇 

I've implemented the mapper configuration as suggested (sorry for missing it), let me know what you think. Giving names also was tough (as usual) 😂

File: README.md [hunk 6]
```diff
@@ -68,6 +68,8 @@ Annotate your test class with the `@ZeebeProcessTest` annotation. This annotatio
 
 1. It will manage the [lifecycle](#engine-lifecycle) of the testcontainer / embedded test engine
 2. It will create a client which can be used to interact with the engine.
+   1. A custom `ObjectMapper` can be provided to the client by simply create and configure an
+      instance of it in the test class.
```
Comment (remcowesterhoud) [inline README.md:72]:
```suggestion
   1. A [custom ObjectMapper](#custom-mapper) can be provided to the client by simply create and configure an
      instance of it in the test class.
```

🔧 Some grammatical fixes and let's reference to the section.

File: README.md [hunk 7]
```diff
@@ -215,6 +217,25 @@ IncidentAssert assertions = BpmnAssert.assertThat(activatedJob)
...
+  ...
+  private ObjectMapper mapper = setupMapper();
+
+
+  private ObjectMapper setupMapper() {
+    ObjectMapper objectMapper = new ObjectMapper();
+    .... // custom configuration
+    return objectMapper;
+  }
+}
```
Comment (remcowesterhoud) [inline README.md:236]:
```suggestion
@ZeebeProcessTest
class MyProcessTest {
  private ZeebeTestEngine engine;
  private ZeebeClient client;
  private ObjectMapper mapper = setupMapper();


  private ObjectMapper setupMapper() {
    ObjectMapper objectMapper = new ObjectMapper();
    // custom configuration
    return objectMapper;
  }
}
```

🙃 Just just my personal preference for this example

File: extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/ZeebeProcessTestExtension.java [hunk 8]
```diff
@@ -193,4 +191,21 @@ private Optional<ObjectMapper> getCustomMapper(final ExtensionContext context) {
...
+
+  /**
+   * Create a {@link ZeebeClient}. If a custom {@link ObjectMapper} is provided it is initialized into
+   * the {@link ObjectMapperConfig} and it is configured into the client
+   * @param objectMapper an {@link Optional} of {@link ObjectMapper}
+   * @param engine the used engine
+   * @return a zeebe client
+   */
+  private ZeebeClient createClient(
+      final Optional<ObjectMapper> objectMapper, final ContainerizedEngine engine) {
```
Comment (remcowesterhoud) [inline extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/ZeebeProcessTestExtension.java:204]: 🔧 Optional shouldn't be passed as a parameter. This also made me realise we can make this code a lot more clean.

In the `getCustomMapper` method we can always return an `ObjectMapper`. If the user configured one we return this one, else we return `new ObjectMapper()`. This gets rid of all these checks and behaves the same as now, as an empty ObjectMapper is the default our client uses.

File: api/src/main/java/io/camunda/zeebe/process/test/api/ObjectMapperConfig.java [hunk 9]
```diff
@@ -0,0 +1,38 @@
...
+ */
+
+package io.camunda.zeebe.process.test.api;
+
+import com.fasterxml.jackson.databind.ObjectMapper;
+
+/**
+ * Shared custom {@link ObjectMapper} configured by the user
+ */
+public abstract class ObjectMapperConfig {
```
Comment (remcowesterhoud) [inline api/src/main/java/io/camunda/zeebe/process/test/api/ObjectMapperConfig.java:22]: ❓ ❌  I struggle to understand why we need to config class in the api. AFAIk it's only used by the assertions and to create a client to the engine. We also don't expect users to interact with this config class.
The classes in this api module are the classes that get injected into the user's test classes by the extension. The implementations of those interfaces both do something very different as they directly interact with the engine, which in some cases is running in a docker container, and in others it's embedded and easier to access.

I would've expected to configuration class to set in the `assertions` module. Similar to how we keep track of the `RecordStream` in the `BpmnAssert` class.

This removes the need to have this class duplicated 3 times as well. The extension sets the field in the config class. The assertions can access this when they need it.

File: assertions/src/main/java/io/camunda/zeebe/process/test/assertions/VariablesMapAssert.java [hunk 10]
```diff
@@ -32,11 +31,13 @@
  */
 public class VariablesMapAssert extends AbstractAssert<VariablesMapAssert, Map<String, String>> {
 
-  static final ObjectMapper JSON_MAPPER = new ObjectMapper();
-  private static final ZeebeObjectMapper OBJECT_MAPPER = new ZeebeObjectMapper();
+  private static ZeebeObjectMapper OBJECT_MAPPER = new ZeebeObjectMapper();
 
   static {
-    JSON_MAPPER.configure(JsonParser.Feature.ALLOW_SINGLE_QUOTES, true);
+    final ObjectMapper customMapper = ObjectMapperConfig.getObjectMapper();
```
Comment (remcowesterhoud) [inline assertions/src/main/java/io/camunda/zeebe/process/test/assertions/VariablesMapAssert.java:37]: ❌ The `getObjectMapper` method should never return null. This should either return the default config mapper we have, or the custom one that was initialised.

It might even be easier to have the config class store a `ZeebeObjectMapper` directly, instead of an `ObjectMapper`. Then we can easily say

```java
private static ZeebeObjectMapper OBJECT_MAPPER = ObjectMapperConfig.getObjectMapper();
```

This way we can get rid of this dirty static code block as well, assuming we configure the mapper accordingly when initialising it in the configuration.

File: qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractProcessInstanceAssertTest.java [hunk 11]
```diff
@@ -1435,4 +1439,47 @@ public void testShouldCaptureLatestValueOfVariable()
           .hasVariableWithValue(ProcessPackLoopingServiceTask.TOTAL_LOOPS, "3");
     }
   }
+
+  @Nested
+  class CustomMapperTests {
```
Comment (remcowesterhoud) [inline qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractProcessInstanceAssertTest.java:1444]: 🔧 This class is huge 😅 Let's create a new test class to verify the custom mapper.

File: qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractProcessInstanceAssertTest.java [hunk 12]
```diff
@@ -1435,4 +1439,47 @@ public void testShouldCaptureLatestValueOfVariable()
...
+    @Test
+    public void shouldDeserializeDateVariables() throws InterruptedException, TimeoutException {
+      final Map<String, Object> variables = new HashMap<>();
+      variables.put("stringProperty", "stringValue");
+      variables.put("numberProperty", 123);
+      variables.put("booleanProperty", true);
+      variables.put("complexProperty", Arrays.asList("Element 1", "Element 2"));
+      variables.put("nullProperty", null);
+      variables.put("javaDate", LocalDateTime.of(2023, 8, 14, 16, 0, 0));
+      variables.put("stringDate", "\"2023-08-14T16:00:00\"");
```
Comment (remcowesterhoud) [inline qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractProcessInstanceAssertTest.java:1460]: 🔧 This would be a great candidate for a [parametrised test](https://www.baeldung.com/parameterized-tests-junit-5#6-method) 🙂

File: assertions/pom.xml [hunk 13]
```diff
@@ -32,6 +32,11 @@
       <artifactId>zeebe-process-test-filters</artifactId>
     </dependency>
 
+    <dependency>
+      <groupId>io.camunda</groupId>
+      <artifactId>zeebe-process-test-api</artifactId>
+    </dependency>
+
```
Comment (remcowesterhoud) [inline assertions/pom.xml:39]: ❌ This dependency shouldn't be necessary if you follow my other comments

**Review by remcowesterhoud — CHANGES_REQUESTED** [review]
That's already better @nicpuppa 🚀 I still have a bunch of comments to improve it further. Please have a look and let me know if you have any questions 👀!

File: api/src/main/java/io/camunda/zeebe/process/test/api/ObjectMapperConfig.java (hunk 9 above)
Comment (nicpuppa) [reply api/src/main/java/io/camunda/zeebe/process/test/api/ObjectMapperConfig.java:22]: I thought the api was the only place where put shared infos, but I was wrong. This suggestion make the code more clear and efficient. Thank you 🙏

File: assertions/src/main/java/io/camunda/zeebe/process/test/assertions/VariablesMapAssert.java (hunk 10 above)
Comment (nicpuppa) [reply assertions/src/main/java/io/camunda/zeebe/process/test/assertions/VariablesMapAssert.java:37]: I agree, thank you again.

File: qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractProcessInstanceAssertTest.java (hunk 12 above)
Comment (remcowesterhoud) [reply qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractProcessInstanceAssertTest.java:1460]: It removes some complexity from the test. That way you don't need to create a Map in the test class. You don't need the foreach loop to go through all scenarios. And best of all, it will run all the cases even if one of them fails.

Comment (nicpuppa) [reply qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractProcessInstanceAssertTest.java:1460]: Ok got it!

**Comment by nicpuppa** [comment]
Hey @remcowesterhoud, thank you for helping me with the `@ParameterizedTest`. I apply all the changes requested. 

Please have another look 👀

**Review by remcowesterhoud — APPROVED** [review]
Thanks @nicpuppa 🚀 I made some slight changes to make it thread-safe. If you're curious have a look at it. For the rest it all looks great 🏆 

If you read this soon, enjoy your holidays. If not, welcome back 😄 

bors merge
